name: CI

# limit ci building to pushes to master not to get twice the notification email
# from github.
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches: '*'

jobs:
  interledger:
    env:
      RUST_LOG: "interledger=trace"
      RUST_BACKTRACE: "full"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server redis-tools libssl-dev

      - name: Install rust toolchain
        uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable
          components: clippy, rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --all-features --all-targets

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Audit
        # FIXME: Disabled:
        # 1. spin: is no longer actively maintained
        # 2. sized-chunks: no safe upgrade.
        # 3. net2: has been removed from crates, still present as a dep to tokio
        run: cargo audit --ignore RUSTSEC-2019-0031 --ignore RUSTSEC-2020-0041 --ignore RUSTSEC-2020-0016

      - name: Test
        run: timeout 15m cargo test --all --all-features

  interledger-packet:
    env:
      RUST_LOG: "interledger=trace"
      RUST_BACKTRACE: "full"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build -p interledger-packet

      - name: Test
        run: timeout 15m cargo test -p interledger-packet
      - name: Test --features strict
        run: timeout 15m cargo test -p interledger-packet --features strict
      - name: Test --features roundtrip-only
        run: timeout 15m cargo test -p interledger-packet --features roundtrip-only

  interledger-stream:
    env:
      RUST_LOG: "interledger=trace"
      RUST_BACKTRACE: "full"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build -p interledger-stream

      - name: Test
        run: timeout 15m cargo test -p interledger-stream
      - name: Test --features strict
        run: timeout 15m cargo test -p interledger-stream --features strict
      - name: Test --features roundtrip-only
        run: timeout 15m cargo test -p interledger-stream --features roundtrip-only

  interledger-btp:
    env:
      RUST_LOG: "interledger=trace"
      RUST_BACKTRACE: "full"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build -p interledger-btp

      - name: Test
        run: timeout 15m cargo test -p interledger-packet
      - name: Test --features strict
        run: timeout 15m cargo test -p interledger-packet --features strict

  test-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 'v12.18.4'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server redis-tools libssl-dev

          # install components (ganache-cli ilp-settlement-xrp conventional-changelog-cli)
          npm install -g ganache-cli ilp-settlement-xrp conventional-changelog-cli

      - name: Test
        run: |
          scripts/run-md-test.sh '^.*$' 1

      - name: 'Store artifacts'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: run-md-test
          path: /tmp/run-md-test

